export default [
	{
		name:"getCodeInfoByUserId",
		method:'post',
		url:'/api/company/getCodeInfoByUserId'
	},
	{
		name:"zhongxinbaoApply",
		method:'post',
		url:'/api/company/zhongxinbaoApply'
	},
	{
		name:"zhongxinbaoApprove",
		method:'post',
		url:'/api/company/zhongxinbaoApprove'
	},
	{
		name:"getApplyProgressList",
		method:'post',
		url:'/api/company/getApplyProgressList'
	},
	{
		name:"getPDFListAll",
		method:'post',
		url:'/api/company/getPDFListAll'
	},
	{
		name:"getAllBusinessInfo",
		method:'post',
		url:'/api/company/zhongxinbao/getAllBusinessInfo'
	},
	{
		name:"getAllCompanyLevel",
		method:'post',
		url:'/api/company/getAllCompanyLevel'
	},
]